frr version 10.7.1_git
frr defaults traditional
hostname spine2
service integrated-vtysh-config
!
ip prefix-list LOOPBACKS seq 5 permit 10.255.0.0/24 le 32
!
route-map TO-BACKBONE permit 10
 match ip address prefix-list LOOPBACKS
exit
!
route-map ADVERTISE-LOOPBACKS permit 10
 match ip address prefix-list LOOPBACKS
exit
!
interface eth1
 ip address 10.0.14.2/30
 ip ospf area 0
 ip ospf network point-to-point
exit
!
interface eth2
 ip address 10.0.24.2/30
 ip ospf area 0
 ip ospf network point-to-point
exit
!
interface eth3
 ip address 10.0.46.1/30
exit
!
interface lo
 ip address 10.255.0.4/32
 ip ospf area 0
exit
!
router bgp 65001
 neighbor 10.0.46.2 remote-as 65100
 !
 address-family ipv4 unicast
  redistribute ospf route-map TO-BACKBONE
  neighbor 10.0.46.2 route-map ADVERTISE-LOOPBACKS out
 exit-address-family
exit
!
router ospf
 ospf router-id 10.255.0.4
 default-information originate always
exit
!
