frr version 10.7.1_git
frr defaults traditional
hostname spine2
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.14.2/30
 ip ospf area 0
 ip ospf network point-to-point
exit
!
interface eth2
 ip address 10.0.24.2/30
 ip ospf area 0
 ip ospf network point-to-point
exit
!
interface lo
 ip address 10.255.0.4/32
 ip ospf area 0
exit
!
router ospf
 ospf router-id 10.255.0.4
exit
!
